apps/simulacion/urls.py
from django.urls import path,re_path
from apps.simulacion import views
from django.contrib.auth.decorators import login_required
app_name = 'simulacion'
urlpatterns = [
    path('', views.index, name="index"),
	path('nuevo', (views.simulacion_view), name="new"),
	path('resultados', (views.simulacion_list), name="simulacion_listar"),
	re_path(r'^editar/(?P<id>\d+)/$', views.simulacion_edit, name="simulacion_editar"),

	]

simuladorBsim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,logout_then_login,LogoutView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('simulacion/', include ('apps.simulacion.urls', namespace="simulacion")),
    path('produccion/', include ('apps.produccion.urls')),
    path('registro/', include ('apps.registro.urls')),
    path('ingresar', LoginView.as_view(template_name='index.html'), name = 'login'),
    #path('', LoginView.as_view(template_name='welcome.html'), name = 'welcome'),
    path('', LogoutView.as_view(template_name='welcome.html'), name='logout')


]

apps/simulacion/models.py
from django.db import models
from apps.registro.models import usuario
from apps.produccion.models import Cosecha
from django.contrib.auth.models import User

# Create your models here.
class SimulacionCostoProduccion (models.Model):
	tipoSuelo = models.CharField(max_length = 20)
	fosforo = models.DecimalField(max_digits = 5, decimal_places = 2,null = True)
	potasio = models.DecimalField(max_digits = 5, decimal_places = 2,null = True)
	calcio =models.DecimalField(max_digits = 5, decimal_places = 2,null = True) 
	magnesio =models.DecimalField(max_digits = 5, decimal_places = 2,null = True)
	boro = models.DecimalField(max_digits = 5, decimal_places = 2,null = True)
	zinc =models.DecimalField(max_digits = 5, decimal_places = 2,null = True)
	ph=models.DecimalField(max_digits = 5, decimal_places = 2,null = True)
	profundidad = models.DecimalField(max_digits = 5, decimal_places = 2)
	sistemaDrenaje = models.CharField(max_length = 20)
	plagas =  models.CharField(max_length = 20)
	deshoje =  models.CharField(max_length = 20)
	embolse =  models.CharField(max_length = 20)
	lvlMar = models.DecimalField(max_digits = 5, decimal_places = 2)
	temperatura = models.DecimalField(max_digits = 5, decimal_places = 2)
	pluviosidad = models.DecimalField(max_digits = 5, decimal_places = 2)
	luminosidad = models.DecimalField(max_digits = 5, decimal_places = 2)
	usuarioSim = models.ForeignKey(User,null = True, blank = True, on_delete = models.CASCADE)
	cosecha = models.ForeignKey(Cosecha,null = True, blank = True, on_delete = models.CASCADE)
	fechaSim= models.DateField(null = True)
	puntajeSimu = models.IntegerField(null = True)
	numHectareas=models.DecimalField(max_digits = 5, decimal_places = 4,null=True)
	numPlantas=models.IntegerField(null = True)

apps/simulacion/forms.py
from django import forms
from apps.simulacion.models import SimulacionCostoProduccion

class SimulacionForm(forms.ModelForm):
	
	class Meta:
		model = SimulacionCostoProduccion

		fields = [

			
			'profundidad',
			'sistemaDrenaje',
			'plagas',
			'deshoje',
			'embolse',
			'lvlMar',
			'temperatura',
			'luminosidad',
			'fechaSim',
			'pluviosidad',
			'tipoSuelo',
			'fosforo',
			'potasio',
			'magnesio',
			'calcio',
			'ph',
			'zinc',
			'boro',

			


		]
		labels = {

			
			'profundidad': 'Profundidad (en metros)',
			'sistemaDrenaje': 'Sistema de drenaje (si o no)',
			'plagas': 'Plagas ( si o no )',
			'deshoje': 'Deshoje (periodico o no)',
			'embolse': 'Embolse ( si o no )',
			'lvlMar': 'Nivel del mar(en metros)',
			'temperatura': 'Temperatura(grados celcios)',
			'luminosidad': 'luminosidad(horas de luz por planta al dia)',
			'densidadSiembra': 'Densidad de siembra',
			'fechaSim': 'Fecha de Simulacion (ingresar año-mes-dia)',
			
			'pluviosidad': 'Pluviosidad por planta (Mensual en ml)',
			'tipoSuelo' : 'Tipo de suelo (arido, arcilloso o franco)',
			'fosforo': 'Nivel de fosforo del suelo',
			'potasio':	'Nivel de potasio del suelo',
			'magnesio': 'Nivel de magnesio en el suelo',
			'calcio': 'Nivel de Calcio  del suelo',
			'ph': 'Nivel de PH del suelo',
			'zinc': 'Nivel de Zinc del suelo',
			'boro':'boro',
			



		}
		widgets = {


			

			'profundidad': forms.NumberInput(attrs={'class': 'form-control'}),
			'sistemaDrenaje': forms.TextInput(attrs={'class': 'form-control'}),
			'plagas': forms.TextInput(attrs={'class': 'form-control'}),
			'deshoje': forms.TextInput(attrs={'class': 'form-control'}),
			'embolse': forms.TextInput(attrs={'class': 'form-control'}),
			'lvlMar': forms.NumberInput(attrs={'class': 'form-control'}),
			'temperatura': forms.NumberInput(attrs={'class': 'form-control'}),
			'luminosidad': forms.NumberInput(attrs={'class': 'form-control'}),
			'densidadSiembra': forms.NumberInput(attrs={'class': 'form-control'}),
			'fechaSim': forms.TextInput(attrs={'class': 'form-control'}),
			'pluviosidad': forms.NumberInput(attrs={'class': 'form-control'}),
			'tipoSuelo' : forms.TextInput(attrs={'class': 'form-control'}),
			'fosforo':forms.NumberInput(attrs={'class': 'form-control'}),
			'potasio':forms.NumberInput(attrs={'class': 'form-control'}),
			'magnesio':forms.NumberInput(attrs={'class': 'form-control'}),
			'calcio':forms.NumberInput(attrs={'class': 'form-control'}),
			'ph':forms.NumberInput(attrs={'class': 'form-control'}),
			'zinc':forms.NumberInput(attrs={'class': 'form-control'}),
			'boro':forms.NumberInput(attrs={'class': 'form-control'}),




		}

apps/simulacion/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.simulacion.forms import SimulacionForm
from apps.simulacion.models import SimulacionCostoProduccion
from apps.produccion.models import Produccion,Cosecha
from apps.registro.models import usuario
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User


# Create your views here.
@login_required(login_url ='/ingresar')
def index(request):
	return render(request,'simulacion/index.html')
	

@login_required(login_url ='/ingresar')
def simulacion_view (request):
	objetoCosecha= ()
	if request.method == 'POST':
		if 'btnFormSim' in request.POST:
			usuario1 = ()
			usuario1 =  request.user
			usuariosim = ()
			
			tipoSuelo = request.POST.get('tipoSuelo')
			profundidad = float(request.POST.get('profundidad'))
			sistemaDrenaje = request.POST.get('sistemaDrenaje')
			plagas =  request.POST.get('plagas')
			deshoje = request.POST.get('deshoje')
			embolse =  request.POST.get('embolse')
			lvlMar =float(request.POST.get('lvlMar'))
			temperatura =float( request.POST.get('temperatura'))
			pluviosidad = float(request.POST.get('pluviosidad'))
			luminosidad = float(request.POST.get('luminosidad'))
			
			fechaSim= request.POST.get('fechaSim')
			fosforo =float(request.POST.get('fosforo'))
			potasio =float(request.POST.get('potasio'))
			calcio =float(request.POST.get('calcio'))
			magnesio =float(request.POST.get('magnesio'))
			boro =float(request.POST.get('boro'))
			zinc =float(request.POST.get('zinc'))
			ph =float(request.POST.get('ph'))
			



			if tipoSuelo == 'arido' :
				puntajeSuelo = 2
			elif tipoSuelo == 'arcilloso':
				puntajeSuelo = 5
			elif tipoSuelo == 'franco':
				puntajeSuelo == 15

			if profundidad >1.2 and profundidad< 1.5 :
				puntajeProfu = 15
			else:
				puntajeProfu = 5

			if sistemaDrenaje == 'si':
				puntajeDrenaje = 15
			else:
				puntajeDrenaje  = 2

			if plagas == 'si' :
				puntajePlagas = 2
			else:
				puntajePlagas = 15

			if deshoje == 'periodico':
				puntajeDeshoje = 15
			elif deshoje == 'no':
				puntajeDeshoje = 2
			else:
				puntajeDeshoje = 5

			if lvlMar > 500 and lvlMar < 1000:
				puntajeMar = 15
			else:
				puntajeMar = 5

			if temperatura == 27:
				puntajeTemp = 15
			elif temperatura > 21 and temperatura < 30:
				puntajeTemp = 10
			else:
			 	puntajeTemp = 2

			if pluviosidad > 101 and pluviosidad < 180:
			 	puntajePluvi = 15
			elif pluviosidad < 100:
			 	puntajePluvi = 5
			else:
			 	puntajePluvi = 10

			if luminosidad > 4 and luminosidad < 6 :
			 	puntajeLumi = 15
			else:
			 	puntajeLumi = 5

			if fosforo >20:
			 	puntajeFosforo = 5
			elif fosforo < 10:
			 	puntajeFosforo = 5
			else:
			 	puntajeFosforo = 15

			if potasio>0.5:
				puntajePotasio = 5
			elif potasio <0.5:
				puntajePotasio = 5
			else:
				puntajePotasio = 15

			if calcio > 6:
				puntajeCalcio = 5
			elif calcio < 3:
				puntajeCalcio = 2
			else:
				puntajeCalcio = 15

			if magnesio > 3:
				puntajeMagnesio= 5
			elif magnesio < 1:
				puntajeMagnesio= 2
			else:
				puntajeMagnesio = 15

			if boro > 0.7:
				puntajeBoro =5
			elif boro < 0.2:
				puntajeBoro = 2
			else:
				puntajeBoro = 15

			if zinc > 15:
				puntajeZinc = 5
			elif zinc < 3:
				puntajeZinc = 2
			else:
				puntajeZinc = 15

			if ph> 6.5:
				puntajePh = 5
			elif ph < 5:
				puntajePh = 5
			else:
				puntajePh = 15

			if embolse == ' si':
				puntajeEmbolse = 15
			else:
				puntajeEmbolse = 5

			puntajeSim = 0
			puntajeSim = (puntajeEmbolse+puntajeSuelo+puntajeProfu+puntajeDrenaje+puntajePlagas+puntajeDeshoje+puntajeMar+puntajeTemp+
				puntajePluvi+puntajeLumi+puntajeFosforo+puntajePotasio+puntajeCalcio+puntajeMagnesio+puntajeBoro+puntajeZinc+puntajePh)

			objetoSimulacion  = SimulacionCostoProduccion(usuarioSim = usuario1, tipoSuelo=tipoSuelo, sistemaDrenaje = sistemaDrenaje,
				plagas = plagas, deshoje = deshoje, embolse =embolse , lvlMar = lvlMar, temperatura = temperatura,
				pluviosidad = pluviosidad, luminosidad = luminosidad, fechaSim = fechaSim, puntajeSimu = puntajeSim, profundidad = profundidad, fosforo = fosforo, potasio = potasio,calcio = calcio, magnesio = magnesio,
				boro = boro, zinc = zinc, ph = ph)
			objetoSimulacion.save()

			if puntajeSim > 240 and puntajeSim <270:
				objetoCosecha = Cosecha.objects.get(id = 3)

			if puntajeSim > 210 and puntajeSim <240:
				objetoCosecha = Cosecha.objects.get(id = 4)

			if puntajeSim > 180 and puntajeSim <210:
				objetoCosecha = Cosecha.objects.get(id = 5)

			if puntajeSim > 120 and puntajeSim <180:
				objetoCosecha = Cosecha.objects.get(id = 6)

			if puntajeSim > 90 and puntajeSim <120:
				objetoCosecha = Cosecha.objects.get(id = 7)

			if puntajeSim > 60 and puntajeSim <90:
				objetoCosecha = Cosecha.objects.get(id = 8)

			if puntajeSim < 60:
				objetoCosecha = Cosecha.objects.get(id = 9)


			form = SimulacionForm(request.POST)
		
	else:
		
		form= SimulacionForm()
	contexto = {
	'form' : form,
	'objetoCosecha' : objetoCosecha,
	}
	#print(objetoCosecha.grosorTallo)
	return render(request, 'simulacion/simulacion_form.html', {'contexto':contexto})

@login_required(login_url='/ingresar')
def simulacion_list(request):
	simulacion = SimulacionCostoProduccion.objects.filter(usuarioSim =request.user)
	contexto = {'simulaciones': simulacion}

	return render(request, 'simulacion/simulacion_list.html', contexto)
@login_required(login_url ='/ingresar')

def simulacion_edit(request,id):
	objetoCosecha= ()
	simulacion = SimulacionCostoProduccion.objects.get(id = id)
	if request.method=='GET':
	 	form = SimulacionForm(instance = simulacion)
	elif request.method == 'POST':
	 	form = SimulacionForm(request.POST, instance = simulacion)
	 	if form.is_valid():
	 		form.save()
	 	if 'btnFormSim' in request.POST:
	 		usuarioSim=()
	 		usuario1 = request.user


	 		tipoSuelo = request.POST.get('tipoSuelo')
	 		profundidad = float(request.POST.get('profundidad'))
	 		sistemaDrenaje = request.POST.get('sistemaDrenaje')
	 		plagas =  request.POST.get('plagas')
	 		deshoje = request.POST.get('deshoje')
	 		embolse =  request.POST.get('embolse')
	 		lvlMar =float(request.POST.get('lvlMar'))
	 		temperatura =float( request.POST.get('temperatura'))
	 		pluviosidad = float(request.POST.get('pluviosidad'))
	 		luminosidad = float(request.POST.get('luminosidad'))
	 		fechaSim= request.POST.get('fechaSim')
	 		fosforo =float(request.POST.get('fosforo'))
	 		potasio =float(request.POST.get('potasio'))
	 		calcio =float(request.POST.get('calcio'))
	 		magnesio =float(request.POST.get('magnesio'))
	 		boro =float(request.POST.get('boro'))
	 		zinc =float(request.POST.get('zinc'))
	 		ph =float(request.POST.get('ph'))



	 		
	 		if tipoSuelo == 'arido':
	 			puntajeSuelo = 2

	 		elif tipoSuelo == 'arcilloso':
	 			puntajeSuelo==10

	 		elif tipoSuelo  == 'franco':
	 			puntajeSuelo = 15
	 		else:
	 			puntajeSuelo = 3

	 		if profundidad >1.2 and profundidad< 1.5 :
	 			puntajeProfu = 15
	 		else:
	 			puntajeProfu = 5

	 		if sistemaDrenaje == 'si':
	 			puntajeDrenaje = 15
	 		else:
	 			puntajeDrenaje = 2

	 		if plagas == 'si' :
	 			puntajePlagas = 2
	 		else:
	 			puntajePlagas = 15

	 		if deshoje == 'periodico':
	 			puntajeDeshoje = 15
	 		elif deshoje == 'no':
	 			puntajeDeshoje = 2

	 		if lvlMar > 500 and lvlMar < 1000:
	 			puntajeMar = 15
	 		else:
	 			puntajeMar = 5

	 		if temperatura == 27:
	 			puntajeTemp = 15
	 		elif temperatura > 21 and temperatura < 30:
	 			puntajeTemp = 10

	 		else:
	 			puntajeTemp = 2

	 		if pluviosidad > 101 and pluviosidad < 180:
	 			puntajePluvi = 15
	 		elif pluviosidad < 100:
	 			puntajePluvi = 5
	 		else:
	 			puntajePluvi = 10

	 		if luminosidad > 4 and luminosidad < 6 :
	 			puntajeLumi = 15
	 		else:
	 			puntajeLumi =5 

	 		if fosforo >20:
	 			puntajeFosforo = 5
	 		elif fosforo < 10:
	 			puntajeFosforo = 5
	 		else:
	 			puntajeFosforo = 15

	 		if potasio > 0.5:
	 			puntajePotasio = 5
	 		elif potasio < 0.5:
	 			puntajePotasio = 5
	 		else:
	 			puntajePotasio = 15

	 		if calcio > 6:
	 			puntajeCalcio = 5
	 		elif calcio < 3:
	 			puntajeCalcio =2 
	 		else:
	 			puntajeCalcio = 15

	 		if magnesio > 3:
	 			puntajeMagnesio = 5
	 		if magnesio <1:
	 			puntajeMagnesio = 2
	 		else: 
	 			puntajeMagnesio = 15

	 		if boro > 0.7:
	 			puntajeBoro = 5
	 		elif boro < 0.2 :
	 			puntajeBoro = 2
	 		else: 
	 			puntajeBoro = 15

	 		if zinc > 15:
	 			puntajeZinc = 5
	 		elif zinc < 3:
	 			puntajeZinc =2 
	 		else:
	 			puntajeZinc = 15

	 		if ph> 6.5:
	 			puntajePh = 5
	 		elif ph < 5:
	 			puntajePh = 5
	 		else:
	 			puntajePh = 15
	 		
	 		if embolse == 'si':
	 			puntajeEmbolse = 15
	 		elif embolse == 'no':
	 			puntajeEmbolse = 10
	 		else:
	 			puntajeEmbolse = 2


	 		puntajeSim=0
	 		
	 		puntajeSim =(puntajeEmbolse+puntajeSuelo+puntajeProfu+puntajeDrenaje+puntajePlagas+puntajeDeshoje+puntajeMar+puntajeTemp+
	 			puntajePluvi+puntajeLumi+puntajeFosforo+puntajePotasio+puntajeCalcio+puntajeMagnesio+puntajeBoro+puntajeZinc+puntajePh)

	 		objetoSimulacion  = SimulacionCostoProduccion(usuarioSim = usuario1, tipoSuelo=tipoSuelo, sistemaDrenaje = sistemaDrenaje,
	 			plagas = plagas, deshoje = deshoje, embolse =embolse , lvlMar = lvlMar, temperatura = temperatura,
	 			pluviosidad = pluviosidad, luminosidad = luminosidad, fechaSim = fechaSim, puntajeSimu = puntajeSim, profundidad = profundidad, fosforo = fosforo, potasio = potasio,calcio = calcio, magnesio = magnesio,
	 			boro = boro, zinc = zinc, ph = ph)


	 		if puntajeSim > 240 and puntajeSim <270:
	 			objetoCosecha = Cosecha.objects.get(id = 3)

	 		if puntajeSim > 210 and puntajeSim <240:
	 			objetoCosecha = Cosecha.objects.get(id = 4)

	 		if puntajeSim > 180 and puntajeSim <210:
	 			objetoCosecha = Cosecha.objects.get(id = 5)

	 		if puntajeSim > 120 and puntajeSim <180:

templates/simulacion/index.html
{% extends 'base/base.html' %}


{% block title %}

Bsim

 
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   
<div class="container">
  <a class="navbar-brand" href="./"><b>Bsim</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
<div class="collapse navbar-collapse" id="navbarSupportedContent">
     
<ul class="navbar-nav mr-auto">
       

       
<li class="nav-item">
        <a class="nav-link" href="resultados">Consulta historial</a>
      </li>
        
<li class="nav-item">
        <a class="nav-link" href="nuevo">Crear Nueva simulacion</a>
      </li>
    </ul>
 
<form class="form-inline my-2 my-lg-0">
    
      
    </form>
 
      <a class="btn btn-danger" href='/'>Salir</a>
      
 
  </div>
 
  </div>
 
</nav>
{% endblock %}﻿

{% block content%}
<style >
#playground-container {
    height: 500px;
    overflow: hidden !important;
    
}
.main{margin-top:70px;
-webkit-box-shadow: 0px 0px 14px 0px rgba(0,0,0,0.24);
-moz-box-shadow: 0px 0px 14px 0px rgba(0,0,0,0.24);
box-shadow: 0px 0px 14px 0px rgba(0,0,0,0.24);
padding:0px;
}
.fb:focus, .fb:hover{color:FFF !important;}
body{
background-image:url(http://animagehub.com/wp-content/uploads/2016/11/Banana-vector-4.png);
background-size: 600px 600px;
background-position: center; 
font-family: 'Raleway', sans-serif;
}
</style>

<h1> <br> <center> <font color=black> Bienvenido usuario comienza a hacer tus simulaciones ya </font></center> </h1>

<h4> <br><center> <font color = green> Recuerda que puedes editar las simulaciones que has realizado anteriormente</font></center></h4>


{% endblock %}

templates/simulacion/simulacion_form.html
{% extends 'base/base.html' %}


{% block title %}

Bsim Simulacion

 
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   
<div class="container">
  <a class="navbar-brand" href="/simulacion"><b>Bsim</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
<div class="collapse navbar-collapse" id="navbarSupportedContent">
     
<ul class="navbar-nav mr-auto">
       
<li class="nav-item">
        <a class="nav-link" href='/simulacion'>Inicio <span class="sr-only">(current)</span></a>
        </li>
       
<li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
 
    </ul>
 
<form class="form-inline my-2 my-lg-0">
    
      
    </form>
 
      <a class="btn btn-danger" href='/logout'>Salir</a>
  </div>
 
  </div>
 
</nav>
   {% endblock %}﻿  






{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm">
      <h6> introduzca los datos, tenga en cuenta que son datos para una simulacion de 1 hectarea y con un precio de $2.00 el Kg</h6>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {{contexto.form.as_p}}
        <button type="submit"  name = "btnFormSim" > Generar Simulacion </button>
      </form>

<br>
</div>
    <div class="col-sm6">
      {% if contexto.objetoCosecha %}
        <table class="table table-striped">
 	        <thead>
    	       <tr>
      		    <th scope="col">Altura planta (cm)</th>
      		    <th scope="col"> Grosor tallo (cm)</th>
      		    <th scope="col">numero de hojas por mes</th>
      		    <th scope="col">peso de racimo</th>
      		    <th scope="col"> Nota de calidad del cultivo</th>
      		    <th scope="col"> Kilogramos cosechados</th>
      		    <th scope="col"> Precio por Kg</th>
      		    <th scope="col"> Utilidad esperada ($)</th>
              <th scope="col"></th>
    
		        </tr>
	       </thead>
	       <tbody>
		      <tr>
      		  <td>{{contexto.objetoCosecha.alturaPlanta}}</td>
      		  <td>{{contexto.objetoCosecha.grosorTallo}}</td>
      		  <td> {{contexto.objetoCosecha.numeroHojas}}</td>
      		  <td> {{contexto.objetoCosecha.pesoRacimo}}</td>
      		  <td>{{contexto.objetoCosecha.costoHectarea}}</td>
      		  <td>{{contexto.objetoCosecha.kgCosechados}}</td>
      		  <td>{{contexto.objetoCosecha.precioKg}}</td>
      		  <td>{{contexto.objetoCosecha.utilidadEsperada}}</td>
            <td> <a href="{% url 'simulacion:simulacion_listar'  %}"  class="btn btn-light">Finalizar</a> </td>





           </tr>
 	      </tbody>
      </table>


        {% else %}
 	        <h1></h1> 
        {%endif%}
  </div>
</div>
</div>


{% endblock %}

templates/simulacion/simulacion_list.html
{% extends 'base/base.html' %}

{% block title %}

Bsim

 
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   
<div class="container">
  <a class="navbar-brand" href='/simulacion'><b>Bsim </b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
<div class="collapse navbar-collapse" id="navbarSupportedContent">
     
<ul class="navbar-nav mr-auto">
       
<li class="nav-item">
        <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
        </li>
       
<li class="nav-item">
        <a class="nav-link" href='nuevo'>Nueva simulacion</a>
      </li>
 
    </ul>
 
<form class="form-inline my-2 my-lg-0">
    
      
    </form>
 
      
      <a class="btn btn-outline-warning d-lg-inline-block mb-3 mb-md-0 ml-md-3" href='/'>SALIR</a>
 
  </div>
 
  </div>
 
</nav>
   {% endblock %}﻿  

{% block content %}

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">fecha simulacion</th>
      <th scope="col"> Tipo de suelo</th>
      <th scope="col">Profundidad</th>
      <th scope="col">Sistema de drenaje</th>
      <th scope="col">Plagas</th>
      <th scope="col"> Desohe </th>
      <th scope="col">Embolse</th>
      <th scope="col">Nivel del mar</th>
      <th scope="col">Temperatura</th>
      <th scope="col">Pluviosidad</th>
      <th scope="col"> Luminosidad</th>
      
     
      <th scope="col"></th>
     
      
      
    </tr>
  </thead>
  <tbody>
    {% if simulaciones %}
    {% for simulacion in simulaciones %}
    

    
    <tr>
      <td>{{simulacion.fechaSim}}</td>
      <td>{{simulacion.tipoSuelo}}</td>
      <td> {{simulacion.profundidad}}</td>
      <td> {{simulacion.sistemaDrenaje}}</td>
      <td>{{simulacion.plagas}} </td>
      <td>{{simulacion.deshoje}}</td>
      <td>{{simulacion.embolse}}</td>
      <td>{{simulacion.lvlMar}}</td>
      <td>{{simulacion.temperatura}}</td>
      <td>{{simulacion.pluviosidad}}</td>
      <td>{{simulacion.luminosidad}}</td>
      
     


      <td> <a href="{% url 'simulacion:simulacion_editar' simulacion.id %}"  class="btn btn-light">Editar</a> </td>
    
    
    

    {% endfor%}
    {% else %}
    <h1> No se encuentran registros disponibles </h1>

    

    {% endif %}
   
  </tbody>
</table> 

{% endblock %}
    
          
      
     
     
      
       
      
       
      
     
     
      
      
  
      
      
      
    
      
    
   
      
      
    
    
      
    
    
    
   
      
     
    <